### ISSUE TITLE
常用CSS套路

### ISSUE THREAD

**Issue by Evil-Zink** [Evil-Zink/Blog#2]
**本文持续更新，记录常用的CSS套路**
### 清除浮动
```css
.clearfix::after{
    content:  '';
    display: block;
    clear: both;
}
```
---

### 单词换行（文字过长自动换行）
```css
span{
    word-break: break-all;
}
```

---

### 文本溢出
```css
/*单行文本溢出*/
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;


/*多行文本溢出*/
/*WebKit浏览器或移动端实现*/
overflow : hidden;
text-overflow: ellipsis;
display: -webkit-box;
-webkit-line-clamp: 2;
/*-webkit-line-clamp的值代表在第几行省略*/
-webkit-box-orient: vertical;
```

---

### 文字垂直居中
```css
line-height: 20px;
padding: 5px;
```
